# Guess the number

import random

repeat = "yes"
autoGeneratedCode=random.randint(1,20)
print("autoGeneratedCode", autoGeneratedCode)
guessedNumber=int(input("Enter your guess number : "))

def fn_repeat():
	while True:
		repeat=input("Do you wanted to repeat (yes/no): ")
		if repeat == "yes" or repeat == "no":
			break
		else:
			print("invalid : Enter either yes or no")

def trail_guess():
	guessedNumber=int(input("Enter your guess number : "))



"""
while repeat == "yes":
	print("Guessed nubmer is wrong , number is : ", autoGeneratedCode)
	if autoGeneratedCode == guessedNumber:
		print("Guessed number is 100\% correct")
		break
	elif guessedNumber >= autoGeneratedCode:
		print("guessed value is higher than Generated Code")
		repeat=input("Do you wanted to repeat (yes/no) : ")
		guessedNumber=int(input("Enter your guess number : "))
	elif guessedNumber <= autoGeneratedCode:
		print("guessed value is lower than Generated Code")
		repeat=input("Do you wanted to repeat (yes/no) : ")
		guessedNumber=int(input("Enter your guess number : "))
"""

while repeat == "yes":
	print("autoGeneratedCode value is : ", autoGeneratedCode)
	if guessedNumber == autoGeneratedCode:
		print("Guess is right")
		break
	elif guessedNumber >= autoGeneratedCode:
		print("Guess number is greater than Generated")
		fn_repeat()
		trail_guess()
		break
	elif guessedNumber <= autoGeneratedCode:
		print("Guess number is smaller than Generated")
		fn_repeat()
		trail_guess()
		break


#else:
#	print("Guessed number is not correct")