# Guess the number

import random

repeat = "yes"
trailCount = 0
autoGeneratedCode=random.randint(1,20)
print("autoGeneratedCode", autoGeneratedCode)
print(" guess the number with in 3 trails" )

while trailCount<3:
	guessedNumber=int(input("Enter your guess number : "))
	
	if guessedNumber > autoGeneratedCode:
		print("your guess is higher than autoGeneratedCode")
	elif guessedNumber < autoGeneratedCode:
		print("your guess is less than autoGeneratedCode")	
	if autoGeneratedCode == guessedNumber:
		break
	trailCount+=1

if autoGeneratedCode == guessedNumber:
	print("Guess is correct")

if autoGeneratedCode != guessedNumber:
	print("Failed : autoGeneratedCode is : ",autoGeneratedCode)
